### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by QGB** [Docker-Hub-frolvlad/docker-alpine-glibc#61]
```
8b8d6e33dd95:~# uname -a
Linux 8b8d6e33dd95 4.15.0-193-generic #204-Ubuntu SMP Fri Aug 26 19:20:21 UTC 2022 x86_64 Linux
8b8d6e33dd95:~# /root/anaconda3/bin/ipython
Traceback (most recent call last):
  File "/root/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 317, in initialize
    self.init_shell()
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 331, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/configurable.py", line 537, in instance
    inst = cls(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 525, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 661, in __init__
    self.init_history()
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1803, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/history.py", line 551, in __init__
    self.save_thread.start()
  File "/root/anaconda3/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/history.py", line 847, in stop
    self.join()
  File "/root/anaconda3/lib/python3.8/threading.py", line 1006, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
8b8d6e33dd95:~# 

```

**Comment by frol** [comment]
I have seen too many problems with glibc apps running on Alpine, so it is not a huge surprise to me, but it is the unfortunate state of things. I don't have the capacity to investigate and fix the problem, but I am happy to review a PR if someone will find the solution.

**Comment by frol** [comment]
@QGB Try using `frolvlad/alpine-glibc:glibc-2.34` tag instead of the latest as it seems that 2.35 package is actually broken: https://github.com/sgerrand/alpine-pkg-glibc/issues/181

**Comment by QGB** [comment]
same problem

```
docker run -it -p 17681:17681 -p 11122:1122 -v /root:/root -v /:/all  frolvlad/alpine-glibc:glibc-2.34
/ #
/ # /root/anaconda3/bin/ipython
Traceback (most recent call last):
  File "/root/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 317, in initialize
    self.init_shell()
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 331, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/configurable.py", line 537, in instance
    inst = cls(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 525, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 661, in __init__
    self.init_history()
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1803, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/history.py", line 551, in __init__
    self.save_thread.start()
  File "/root/anaconda3/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/history.py", line 847, in stop
    self.join()
  File "/root/anaconda3/lib/python3.8/threading.py", line 1006, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
/ #
```

**Comment by frol** [comment]
Have you tried `frolvlad/alpine-miniconda3` image?

**Comment by QGB** [comment]
sorry

```
docker run -it -p 17681:17681 -p 11122:1122 -v /root:/root -v /:/all  frolvlad/alpine-miniconda3
Unable to find image 'frolvlad/alpine-miniconda3:latest' locally
latest: Pulling from frolvlad/alpine-miniconda3
213ec9aee27d: Already exists
ccd85b3898ec: Already exists
7bbbf974bb8e: Pull complete
Digest: sha256:9c87f8e56ee24c136cc911eb2990dc3914892dac6e8f43590da0179a8ad24947
Status: Downloaded newer image for frolvlad/alpine-miniconda3:latest
/ # /root/anaconda3/bin/ipython
Traceback (most recent call last):
  File "/root/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 317, in initialize
    self.init_shell()
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 331, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/root/anaconda3/lib/python3.8/site-packages/traitlets/config/configurable.py", line 537, in instance
    inst = cls(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 525, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 661, in __init__
    self.init_history()
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1803, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "/root/anaconda3/lib/python3.8/site-packages/IPython/core/history.py", line 551, in __init__
    self.save_thread.start()
  File "/root/anaconda3/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
